/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as LoginRouteImport } from './app/login'
import { Route as DashboardRouteImport } from './app/dashboard'
import { Route as IndexRouteImport } from './app/index'
import { Route as DashboardIndexRouteImport } from './app/dashboard/index'
import { Route as DashboardStatisticsIndexRouteImport } from './app/dashboard/statistics/index'
import { Route as DashboardSettingsIndexRouteImport } from './app/dashboard/settings/index'
import { Route as DashboardRecommendationsIndexRouteImport } from './app/dashboard/recommendations/index'
import { Route as DashboardReadingLogIndexRouteImport } from './app/dashboard/reading-log/index'
import { Route as DashboardQuotesIndexRouteImport } from './app/dashboard/quotes/index'
import { Route as DashboardGenresIndexRouteImport } from './app/dashboard/genres/index'
import { Route as DashboardCalendarIndexRouteImport } from './app/dashboard/calendar/index'
import { Route as DashboardBooksIndexRouteImport } from './app/dashboard/books/index'
import { Route as DashboardAuthorsIndexRouteImport } from './app/dashboard/authors/index'
import { Route as DashboardBooksAddRouteImport } from './app/dashboard/books/add'
import { Route as DashboardBooksBookIdRouteImport } from './app/dashboard/books/$bookId'
import { Route as ApiStatsMarkdownRouteImport } from './app/api/stats/markdown'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatisticsIndexRoute =
  DashboardStatisticsIndexRouteImport.update({
    id: '/statistics/',
    path: '/statistics/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecommendationsIndexRoute =
  DashboardRecommendationsIndexRouteImport.update({
    id: '/recommendations/',
    path: '/recommendations/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReadingLogIndexRoute =
  DashboardReadingLogIndexRouteImport.update({
    id: '/reading-log/',
    path: '/reading-log/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardQuotesIndexRoute = DashboardQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGenresIndexRoute = DashboardGenresIndexRouteImport.update({
  id: '/genres/',
  path: '/genres/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarIndexRoute = DashboardCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBooksIndexRoute = DashboardBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuthorsIndexRoute = DashboardAuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBooksAddRoute = DashboardBooksAddRouteImport.update({
  id: '/books/add',
  path: '/books/add',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBooksBookIdRoute = DashboardBooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiStatsMarkdownRoute = ApiStatsMarkdownRouteImport.update({
  id: '/api/stats/markdown',
  path: '/api/stats/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stats/markdown': typeof ApiStatsMarkdownRoute
  '/dashboard/books/$bookId': typeof DashboardBooksBookIdRoute
  '/dashboard/books/add': typeof DashboardBooksAddRoute
  '/dashboard/authors/': typeof DashboardAuthorsIndexRoute
  '/dashboard/books/': typeof DashboardBooksIndexRoute
  '/dashboard/calendar/': typeof DashboardCalendarIndexRoute
  '/dashboard/genres/': typeof DashboardGenresIndexRoute
  '/dashboard/quotes/': typeof DashboardQuotesIndexRoute
  '/dashboard/reading-log/': typeof DashboardReadingLogIndexRoute
  '/dashboard/recommendations/': typeof DashboardRecommendationsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/statistics/': typeof DashboardStatisticsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stats/markdown': typeof ApiStatsMarkdownRoute
  '/dashboard/books/$bookId': typeof DashboardBooksBookIdRoute
  '/dashboard/books/add': typeof DashboardBooksAddRoute
  '/dashboard/authors': typeof DashboardAuthorsIndexRoute
  '/dashboard/books': typeof DashboardBooksIndexRoute
  '/dashboard/calendar': typeof DashboardCalendarIndexRoute
  '/dashboard/genres': typeof DashboardGenresIndexRoute
  '/dashboard/quotes': typeof DashboardQuotesIndexRoute
  '/dashboard/reading-log': typeof DashboardReadingLogIndexRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/statistics': typeof DashboardStatisticsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stats/markdown': typeof ApiStatsMarkdownRoute
  '/dashboard/books/$bookId': typeof DashboardBooksBookIdRoute
  '/dashboard/books/add': typeof DashboardBooksAddRoute
  '/dashboard/authors/': typeof DashboardAuthorsIndexRoute
  '/dashboard/books/': typeof DashboardBooksIndexRoute
  '/dashboard/calendar/': typeof DashboardCalendarIndexRoute
  '/dashboard/genres/': typeof DashboardGenresIndexRoute
  '/dashboard/quotes/': typeof DashboardQuotesIndexRoute
  '/dashboard/reading-log/': typeof DashboardReadingLogIndexRoute
  '/dashboard/recommendations/': typeof DashboardRecommendationsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/statistics/': typeof DashboardStatisticsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/stats/markdown'
    | '/dashboard/books/$bookId'
    | '/dashboard/books/add'
    | '/dashboard/authors/'
    | '/dashboard/books/'
    | '/dashboard/calendar/'
    | '/dashboard/genres/'
    | '/dashboard/quotes/'
    | '/dashboard/reading-log/'
    | '/dashboard/recommendations/'
    | '/dashboard/settings/'
    | '/dashboard/statistics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/stats/markdown'
    | '/dashboard/books/$bookId'
    | '/dashboard/books/add'
    | '/dashboard/authors'
    | '/dashboard/books'
    | '/dashboard/calendar'
    | '/dashboard/genres'
    | '/dashboard/quotes'
    | '/dashboard/reading-log'
    | '/dashboard/recommendations'
    | '/dashboard/settings'
    | '/dashboard/statistics'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/stats/markdown'
    | '/dashboard/books/$bookId'
    | '/dashboard/books/add'
    | '/dashboard/authors/'
    | '/dashboard/books/'
    | '/dashboard/calendar/'
    | '/dashboard/genres/'
    | '/dashboard/quotes/'
    | '/dashboard/reading-log/'
    | '/dashboard/recommendations/'
    | '/dashboard/settings/'
    | '/dashboard/statistics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStatsMarkdownRoute: typeof ApiStatsMarkdownRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/statistics/': {
      id: '/dashboard/statistics/'
      path: '/statistics'
      fullPath: '/dashboard/statistics/'
      preLoaderRoute: typeof DashboardStatisticsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recommendations/': {
      id: '/dashboard/recommendations/'
      path: '/recommendations'
      fullPath: '/dashboard/recommendations/'
      preLoaderRoute: typeof DashboardRecommendationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reading-log/': {
      id: '/dashboard/reading-log/'
      path: '/reading-log'
      fullPath: '/dashboard/reading-log/'
      preLoaderRoute: typeof DashboardReadingLogIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quotes/': {
      id: '/dashboard/quotes/'
      path: '/quotes'
      fullPath: '/dashboard/quotes/'
      preLoaderRoute: typeof DashboardQuotesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/genres/': {
      id: '/dashboard/genres/'
      path: '/genres'
      fullPath: '/dashboard/genres/'
      preLoaderRoute: typeof DashboardGenresIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar/': {
      id: '/dashboard/calendar/'
      path: '/calendar'
      fullPath: '/dashboard/calendar/'
      preLoaderRoute: typeof DashboardCalendarIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/books/': {
      id: '/dashboard/books/'
      path: '/books'
      fullPath: '/dashboard/books/'
      preLoaderRoute: typeof DashboardBooksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/authors/': {
      id: '/dashboard/authors/'
      path: '/authors'
      fullPath: '/dashboard/authors/'
      preLoaderRoute: typeof DashboardAuthorsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/books/add': {
      id: '/dashboard/books/add'
      path: '/books/add'
      fullPath: '/dashboard/books/add'
      preLoaderRoute: typeof DashboardBooksAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/books/$bookId': {
      id: '/dashboard/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/dashboard/books/$bookId'
      preLoaderRoute: typeof DashboardBooksBookIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/stats/markdown': {
      id: '/api/stats/markdown'
      path: '/api/stats/markdown'
      fullPath: '/api/stats/markdown'
      preLoaderRoute: typeof ApiStatsMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBooksBookIdRoute: typeof DashboardBooksBookIdRoute
  DashboardBooksAddRoute: typeof DashboardBooksAddRoute
  DashboardAuthorsIndexRoute: typeof DashboardAuthorsIndexRoute
  DashboardBooksIndexRoute: typeof DashboardBooksIndexRoute
  DashboardCalendarIndexRoute: typeof DashboardCalendarIndexRoute
  DashboardGenresIndexRoute: typeof DashboardGenresIndexRoute
  DashboardQuotesIndexRoute: typeof DashboardQuotesIndexRoute
  DashboardReadingLogIndexRoute: typeof DashboardReadingLogIndexRoute
  DashboardRecommendationsIndexRoute: typeof DashboardRecommendationsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardStatisticsIndexRoute: typeof DashboardStatisticsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBooksBookIdRoute: DashboardBooksBookIdRoute,
  DashboardBooksAddRoute: DashboardBooksAddRoute,
  DashboardAuthorsIndexRoute: DashboardAuthorsIndexRoute,
  DashboardBooksIndexRoute: DashboardBooksIndexRoute,
  DashboardCalendarIndexRoute: DashboardCalendarIndexRoute,
  DashboardGenresIndexRoute: DashboardGenresIndexRoute,
  DashboardQuotesIndexRoute: DashboardQuotesIndexRoute,
  DashboardReadingLogIndexRoute: DashboardReadingLogIndexRoute,
  DashboardRecommendationsIndexRoute: DashboardRecommendationsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardStatisticsIndexRoute: DashboardStatisticsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStatsMarkdownRoute: ApiStatsMarkdownRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
